### PR TITLE
allow line/offset positioning

### PR DESCRIPTION
**Pull request by sidorares**
There was no way to send, for example 10/10 as a parameter to setDot as it was wrapped in quotes. Added special argument type handling where array of length 2 is treated as val1 / val2 pair and serialised accordingly.

### CODE REVIEW

**Comment by clehner** [comment]
Great! There is one typo: showBaloon should be showBalloon.

**Comment by sidorares** [comment]
fixed!

**Comment by sidorares** [comment]
also, if you happy to merge could you publish it? I bumped minor version 1.0.1 -> 1.1.0 (user-visible backwards compatible api change)

**Comment by clehner** [comment]
Sure thing. Thanks.

**Comment by clehner** [comment]
I just realized there is already showBalloon in VimClient while you've added it to VimBuffer. Did you try client.showBalloon? Are the balloons specific to a buffer?

**Comment by sidorares** [comment]
not sure. Protocol doco example uses version with buffer id: '11:showBalloon!123 "text"' - that's why I was expecting to see it in vim-buffer. It looks like buffer id is ignored and it works identical both ways

**Pull request merged**
